name: persistent
version: 0.7.5
author: Paul Brauner <polux@google.com>
description: Efficient persistent data structures for Dart
homepage: https://github.com/polux/persistent
documentation: http://goo.gl/NTNxHk
environment:
  sdk: '>=0.4.7'
dev_dependencies:
  unittest: any
  enumerators: '>=0.4.0 <0.5.0'
  http: any
  args: any
  propcheck: '>=0.3.5 <0.4.0'
  crypto: any
