name: dart_immutable
description: Efficient immutable data structures for Dart
version: 0.0.1
dependencies:
  dart_check:
    git: https://code.google.com/p/dart-check/
  dart_enumerators:
    git: https://code.google.com/p/dart-enumerators/
  unittest:
    sdk: unittest
