name: persistent
version: 0.0.1
description: Efficient persistent data structures for Dart
author: Paul Brauner <polux@google.com>
homepage: https://code.google.com/p/dart-immutable/
dependencies:
  args:
  unittest:
  propcheck:
  enumerators:
