name: persistent
version: 0.1.1
description: Efficient persistent data structures for Dart
author: Paul Brauner <polux@google.com>
homepage: https://code.google.com/p/dart-immutable/
dependencies:
  args: any
  unittest: any
  propcheck: any
  enumerators: any
