name: persistent
version: 0.5.2
description: Efficient persistent data structures for Dart
author: Paul Brauner <polux@google.com>
homepage: https://code.google.com/p/dart-immutable/
documentation: http://goo.gl/IWWDn
dependencies:
  args: any
  unittest: any
  propcheck: any
  enumerators: any
