name: persistent
version: 0.5.0
description: Efficient persistent data structures for Dart
author: Paul Brauner <polux@google.com>
homepage: https://code.google.com/p/dart-immutable/
documentation: http://doc.dart-immutable.googlecode.com/git/continuous/persistent.html
dependencies:
  args: any
  unittest: any
  propcheck: any
  enumerators: any
