name: persistent
version: 1.0.1
author:
  Paul Brauner <polux@google.com>
  Giovanni Panaro <tsrwebgl@gmail.com>
description: >
  Efficient persistent data structures for Dart.
  "Persistent" means immutable here, not "saved on disk".
homepage: https://github.com/polux/persistent
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  args: any
  http: any
