name: persistent
version: 0.7.1
author: Paul Brauner <polux@google.com>
description: Efficient persistent data structures for Dart
homepage: https://code.google.com/p/dart-immutable/
documentation: http://goo.gl/IWWDn
environment:
  sdk: '>=0.4.7'
dev_dependencies:
  unittest: any
  enumerators: '>=0.4.0 <0.5.0'
  http: any
  args: any
  propcheck: '>=0.3.0 <0.4.0'
